CREATE TABLE USERACCOUNT (id VARCHAR(64) NOT NULL, CreatedDate TIMESTAMP, FirstName VARCHAR(255), LastName VARCHAR(255), Password VARCHAR(255), PreferredName VARCHAR(255), Privilege INTEGER, UserStatus INTEGER, Username VARCHAR(255), PRIMARY KEY (id))
CREATE TABLE NEWS (id VARCHAR(64) NOT NULL, Content VARCHAR(255), CreatedDate TIMESTAMP, Status INTEGER, Title VARCHAR(255), UpdatedDate TIMESTAMP, AuthorId VARCHAR(64), LastUpdateUserId VARCHAR(64), PRIMARY KEY (id))
ALTER TABLE NEWS ADD CONSTRAINT FK_NEWS_AuthorId FOREIGN KEY (AuthorId) REFERENCES USERACCOUNT (id)
ALTER TABLE NEWS ADD CONSTRAINT FK_NEWS_LastUpdateUserId FOREIGN KEY (LastUpdateUserId) REFERENCES USERACCOUNT (id)
